print("Written by: Taino Mendez and Nasir Kelley")
print("The Missing Laptop")
print("Setting: The Computer lab ")
print("Hey did you see my laptop ?")
print("No, I haven't seen it. When was the last time you had it ?")
print("the last time i had it was when it was on the desk over there")
