print("Written by: Taino Mendez and Nasir Kelley")
print("The Missing Laptop")
print("Setting: The Computer lab ")
print("Hey did you see my laptop ?")
print("No, I haven't seen it. When was the last time you had it ?")
print("the last time i had it was when it was on the desk over there")
print("Well, I guess we should look around the lab and see if we can find it.")
print(" wait that's my laptop in the cabinet over there")
print("Oh, I see it. Let's go get it.")
print(" Got it!, i guess the teacher put it there. thank god i found it")
